$wallpaper = /home/bachpro/Imágenes/Wallpapers/hack.jpg

$background = 0xff000000
$foreground = 0xffdddddd

$color0 = 0xff000000
$color1 = 0xff5e655d
$color2 = 0xff6f706f
$color3 = 0xff909190
$color4 = 0xff9ea49e
$color5 = 0xffb2b3b2
$color6 = 0xffbec5be
$color7 = 0xffdddddd
$color8 = 0xff9a9a9a
$color9 = 0xff5e655d
$color10 = 0xff6f706f
$color11 = 0xff909190
$color12 = 0xff9ea49e
$color13 = 0xffb2b3b2
$color14 = 0xffbec5be
$color15 = 0xffdddddd
