$font = Hack Nerd Font

general {
    hide_cursor = true
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = /home/bachpro/Imágenes/Wallpapers/wall0.png 
}

input-field {
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill
    
    outer_color = rgba(225DB1aa) 45deg
    check_color = rgba(ffffffee) rgba(8f8f8fee) 120deg
    fail_color = rgba(ff3333ee) rgba(aa0022ee) 40deg

    fade_on_empty = false
    rounding = 10

    hide_input = false
    font_color = rgb(a1c2e1)        
    dots_size = 0.28               
    dots_spacing = 0.35           
    dots_center = true
    dots_text_format = *

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL$FPRINTFAIL

    check_text = Authenticating...

    position = 0, -140
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME 
    font_size = 90
    font_family = $font

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = -30, -150
    halign = right
    valign = top
}

# label {
#     text = $LAYOUT[es,cl]
#     font_size = 24
#     onclick = hyprctl switchxkblayout all next
# 
#     position = 250, -20
#     halign = center
#     valign = center
# }
