# Shell variables
# Generated by 'wal'
wallpaper='/home/bachpro/Imágenes/Wallpapers/Forest-Dark.png'

# Special
background='#040A10'
foreground='#a1c2e1'
cursor='#a1c2e1'

# Colors
color0='#040A10'
color1='#225DB1'
color2='#4875AB'
color3='#1F60C1'
color4='#3276C5'
color5='#5486B8'
color6='#3D83CB'
color7='#a1c2e1'
color8='#70879d'
color9='#225DB1'
color10='#4875AB'
color11='#1F60C1'
color12='#3276C5'
color13='#5486B8'
color14='#3D83CB'
color15='#a1c2e1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
