foreground   #a1c2e1
background   #040A10
cursor       #a1c2e1

color0       #040A10
color8       #70879d
color1       #225DB1
color9       #225DB1
color2       #4875AB
color10      #4875AB
color3       #1F60C1
color11      #1F60C1
color4       #3276C5
color12      #3276C5
color5       #5486B8
color13      #5486B8
color6       #3D83CB
color14      #3D83CB
color7       #a1c2e1
color15      #a1c2e1
