--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bachpro/Imágenes/Wallpapers/Forest-Dark.png"

-- Special
background="#040A10"
foreground="#a1c2e1"
cursor="#a1c2e1"

-- Colors
color0="#040A10"
color1="#225DB1"
color2="#4875AB"
color3="#1F60C1"
color4="#3276C5"
color5="#5486B8"
color6="#3D83CB"
color7="#a1c2e1"
color8="#70879d"
color9="#225DB1"
color10="#4875AB"
color11="#1F60C1"
color12="#3276C5"
color13="#5486B8"
color14="#3D83CB"
color15="#a1c2e1"
